output = "./db/models"
pkgname = "dbmodel"
no-tests = true
wipe = true

[psql]
dbname = "twinte-db"
host = "db"
port = 5432
user = "postgres"
pass = "password"
sslmode = "disable"
blacklist = ["schema_migrations"]
