// Code generated by "stringer -type=AnnouncementTag -trimprefix=AnnouncementTag -output=announcement_tag_string.gen.go"; DO NOT EDIT.

package announcementdomain

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AnnouncementTagInformation-1]
	_ = x[AnnouncementTagNotification-2]
}

const _AnnouncementTag_name = "InformationNotification"

var _AnnouncementTag_index = [...]uint8{0, 11, 23}

func (i AnnouncementTag) String() string {
	i -= 1
	if i < 0 || i >= AnnouncementTag(len(_AnnouncementTag_index)-1) {
		return "AnnouncementTag(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _AnnouncementTag_name[_AnnouncementTag_index[i]:_AnnouncementTag_index[i+1]]
}
