// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbmodel

var TableNames = struct {
	AlreadyReads            string
	CourseMethods           string
	CourseRecommendedGrades string
	CourseSchedules         string
	Courses                 string
	PaymentUsers            string
	RegisteredCourseTags    string
	RegisteredCourses       string
	Session                 string
	Tags                    string
	UserAuthentications     string
	Users                   string
}{
	AlreadyReads:            "already_reads",
	CourseMethods:           "course_methods",
	CourseRecommendedGrades: "course_recommended_grades",
	CourseSchedules:         "course_schedules",
	Courses:                 "courses",
	PaymentUsers:            "payment_users",
	RegisteredCourseTags:    "registered_course_tags",
	RegisteredCourses:       "registered_courses",
	Session:                 "session",
	Tags:                    "tags",
	UserAuthentications:     "user_authentications",
	Users:                   "users",
}
