// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbmodel

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/sqlboiler/v4/types"
	"github.com/volatiletech/strmangle"
)

// Course is an object representing the database table.
type Course struct {
	ID            string        `boil:"id" json:"id" toml:"id" yaml:"id"`
	Year          int16         `boil:"year" json:"year" toml:"year" yaml:"year"`
	Code          string        `boil:"code" json:"code" toml:"code" yaml:"code"`
	Name          string        `boil:"name" json:"name" toml:"name" yaml:"name"`
	Instructor    string        `boil:"instructor" json:"instructor" toml:"instructor" yaml:"instructor"`
	Credit        types.Decimal `boil:"credit" json:"credit" toml:"credit" yaml:"credit"`
	Overview      string        `boil:"overview" json:"overview" toml:"overview" yaml:"overview"`
	Remarks       string        `boil:"remarks" json:"remarks" toml:"remarks" yaml:"remarks"`
	LastUpdate    time.Time     `boil:"last_update" json:"last_update" toml:"last_update" yaml:"last_update"`
	HasParseError bool          `boil:"has_parse_error" json:"has_parse_error" toml:"has_parse_error" yaml:"has_parse_error"`
	IsAnnual      bool          `boil:"is_annual" json:"is_annual" toml:"is_annual" yaml:"is_annual"`

	R *courseR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L courseL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var CourseColumns = struct {
	ID            string
	Year          string
	Code          string
	Name          string
	Instructor    string
	Credit        string
	Overview      string
	Remarks       string
	LastUpdate    string
	HasParseError string
	IsAnnual      string
}{
	ID:            "id",
	Year:          "year",
	Code:          "code",
	Name:          "name",
	Instructor:    "instructor",
	Credit:        "credit",
	Overview:      "overview",
	Remarks:       "remarks",
	LastUpdate:    "last_update",
	HasParseError: "has_parse_error",
	IsAnnual:      "is_annual",
}

var CourseTableColumns = struct {
	ID            string
	Year          string
	Code          string
	Name          string
	Instructor    string
	Credit        string
	Overview      string
	Remarks       string
	LastUpdate    string
	HasParseError string
	IsAnnual      string
}{
	ID:            "courses.id",
	Year:          "courses.year",
	Code:          "courses.code",
	Name:          "courses.name",
	Instructor:    "courses.instructor",
	Credit:        "courses.credit",
	Overview:      "courses.overview",
	Remarks:       "courses.remarks",
	LastUpdate:    "courses.last_update",
	HasParseError: "courses.has_parse_error",
	IsAnnual:      "courses.is_annual",
}

// Generated where

type whereHelpertypes_Decimal struct{ field string }

func (w whereHelpertypes_Decimal) EQ(x types.Decimal) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelpertypes_Decimal) NEQ(x types.Decimal) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelpertypes_Decimal) LT(x types.Decimal) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpertypes_Decimal) LTE(x types.Decimal) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpertypes_Decimal) GT(x types.Decimal) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpertypes_Decimal) GTE(x types.Decimal) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

type whereHelperbool struct{ field string }

func (w whereHelperbool) EQ(x bool) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperbool) NEQ(x bool) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperbool) LT(x bool) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperbool) LTE(x bool) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperbool) GT(x bool) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperbool) GTE(x bool) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }

var CourseWhere = struct {
	ID            whereHelperstring
	Year          whereHelperint16
	Code          whereHelperstring
	Name          whereHelperstring
	Instructor    whereHelperstring
	Credit        whereHelpertypes_Decimal
	Overview      whereHelperstring
	Remarks       whereHelperstring
	LastUpdate    whereHelpertime_Time
	HasParseError whereHelperbool
	IsAnnual      whereHelperbool
}{
	ID:            whereHelperstring{field: "\"courses\".\"id\""},
	Year:          whereHelperint16{field: "\"courses\".\"year\""},
	Code:          whereHelperstring{field: "\"courses\".\"code\""},
	Name:          whereHelperstring{field: "\"courses\".\"name\""},
	Instructor:    whereHelperstring{field: "\"courses\".\"instructor\""},
	Credit:        whereHelpertypes_Decimal{field: "\"courses\".\"credit\""},
	Overview:      whereHelperstring{field: "\"courses\".\"overview\""},
	Remarks:       whereHelperstring{field: "\"courses\".\"remarks\""},
	LastUpdate:    whereHelpertime_Time{field: "\"courses\".\"last_update\""},
	HasParseError: whereHelperbool{field: "\"courses\".\"has_parse_error\""},
	IsAnnual:      whereHelperbool{field: "\"courses\".\"is_annual\""},
}

// CourseRels is where relationship names are stored.
var CourseRels = struct {
	CourseMethods           string
	CourseRecommendedGrades string
	CourseSchedules         string
}{
	CourseMethods:           "CourseMethods",
	CourseRecommendedGrades: "CourseRecommendedGrades",
	CourseSchedules:         "CourseSchedules",
}

// courseR is where relationships are stored.
type courseR struct {
	CourseMethods           CourseMethodSlice           `boil:"CourseMethods" json:"CourseMethods" toml:"CourseMethods" yaml:"CourseMethods"`
	CourseRecommendedGrades CourseRecommendedGradeSlice `boil:"CourseRecommendedGrades" json:"CourseRecommendedGrades" toml:"CourseRecommendedGrades" yaml:"CourseRecommendedGrades"`
	CourseSchedules         CourseScheduleSlice         `boil:"CourseSchedules" json:"CourseSchedules" toml:"CourseSchedules" yaml:"CourseSchedules"`
}

// NewStruct creates a new relationship struct
func (*courseR) NewStruct() *courseR {
	return &courseR{}
}

func (r *courseR) GetCourseMethods() CourseMethodSlice {
	if r == nil {
		return nil
	}
	return r.CourseMethods
}

func (r *courseR) GetCourseRecommendedGrades() CourseRecommendedGradeSlice {
	if r == nil {
		return nil
	}
	return r.CourseRecommendedGrades
}

func (r *courseR) GetCourseSchedules() CourseScheduleSlice {
	if r == nil {
		return nil
	}
	return r.CourseSchedules
}

// courseL is where Load methods for each relationship are stored.
type courseL struct{}

var (
	courseAllColumns            = []string{"id", "year", "code", "name", "instructor", "credit", "overview", "remarks", "last_update", "has_parse_error", "is_annual"}
	courseColumnsWithoutDefault = []string{"year", "code", "name", "instructor", "credit", "overview", "remarks", "last_update", "has_parse_error"}
	courseColumnsWithDefault    = []string{"id", "is_annual"}
	coursePrimaryKeyColumns     = []string{"id"}
	courseGeneratedColumns      = []string{}
)

type (
	// CourseSlice is an alias for a slice of pointers to Course.
	// This should almost always be used instead of []Course.
	CourseSlice []*Course
	// CourseHook is the signature for custom Course hook methods
	CourseHook func(context.Context, boil.ContextExecutor, *Course) error

	courseQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	courseType                 = reflect.TypeOf(&Course{})
	courseMapping              = queries.MakeStructMapping(courseType)
	coursePrimaryKeyMapping, _ = queries.BindMapping(courseType, courseMapping, coursePrimaryKeyColumns)
	courseInsertCacheMut       sync.RWMutex
	courseInsertCache          = make(map[string]insertCache)
	courseUpdateCacheMut       sync.RWMutex
	courseUpdateCache          = make(map[string]updateCache)
	courseUpsertCacheMut       sync.RWMutex
	courseUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var courseAfterSelectHooks []CourseHook

var courseBeforeInsertHooks []CourseHook
var courseAfterInsertHooks []CourseHook

var courseBeforeUpdateHooks []CourseHook
var courseAfterUpdateHooks []CourseHook

var courseBeforeDeleteHooks []CourseHook
var courseAfterDeleteHooks []CourseHook

var courseBeforeUpsertHooks []CourseHook
var courseAfterUpsertHooks []CourseHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Course) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range courseAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Course) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range courseBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Course) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range courseAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Course) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range courseBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Course) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range courseAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Course) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range courseBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Course) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range courseAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Course) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range courseBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Course) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range courseAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddCourseHook registers your hook function for all future operations.
func AddCourseHook(hookPoint boil.HookPoint, courseHook CourseHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		courseAfterSelectHooks = append(courseAfterSelectHooks, courseHook)
	case boil.BeforeInsertHook:
		courseBeforeInsertHooks = append(courseBeforeInsertHooks, courseHook)
	case boil.AfterInsertHook:
		courseAfterInsertHooks = append(courseAfterInsertHooks, courseHook)
	case boil.BeforeUpdateHook:
		courseBeforeUpdateHooks = append(courseBeforeUpdateHooks, courseHook)
	case boil.AfterUpdateHook:
		courseAfterUpdateHooks = append(courseAfterUpdateHooks, courseHook)
	case boil.BeforeDeleteHook:
		courseBeforeDeleteHooks = append(courseBeforeDeleteHooks, courseHook)
	case boil.AfterDeleteHook:
		courseAfterDeleteHooks = append(courseAfterDeleteHooks, courseHook)
	case boil.BeforeUpsertHook:
		courseBeforeUpsertHooks = append(courseBeforeUpsertHooks, courseHook)
	case boil.AfterUpsertHook:
		courseAfterUpsertHooks = append(courseAfterUpsertHooks, courseHook)
	}
}

// One returns a single course record from the query.
func (q courseQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Course, error) {
	o := &Course{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbmodel: failed to execute a one query for courses")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all Course records from the query.
func (q courseQuery) All(ctx context.Context, exec boil.ContextExecutor) (CourseSlice, error) {
	var o []*Course

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "dbmodel: failed to assign all query results to Course slice")
	}

	if len(courseAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all Course records in the query.
func (q courseQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodel: failed to count courses rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q courseQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "dbmodel: failed to check if courses exists")
	}

	return count > 0, nil
}

// CourseMethods retrieves all the course_method's CourseMethods with an executor.
func (o *Course) CourseMethods(mods ...qm.QueryMod) courseMethodQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"course_methods\".\"course_id\"=?", o.ID),
	)

	return CourseMethods(queryMods...)
}

// CourseRecommendedGrades retrieves all the course_recommended_grade's CourseRecommendedGrades with an executor.
func (o *Course) CourseRecommendedGrades(mods ...qm.QueryMod) courseRecommendedGradeQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"course_recommended_grades\".\"course_id\"=?", o.ID),
	)

	return CourseRecommendedGrades(queryMods...)
}

// CourseSchedules retrieves all the course_schedule's CourseSchedules with an executor.
func (o *Course) CourseSchedules(mods ...qm.QueryMod) courseScheduleQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"course_schedules\".\"course_id\"=?", o.ID),
	)

	return CourseSchedules(queryMods...)
}

// LoadCourseMethods allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (courseL) LoadCourseMethods(ctx context.Context, e boil.ContextExecutor, singular bool, maybeCourse interface{}, mods queries.Applicator) error {
	var slice []*Course
	var object *Course

	if singular {
		var ok bool
		object, ok = maybeCourse.(*Course)
		if !ok {
			object = new(Course)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeCourse)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeCourse))
			}
		}
	} else {
		s, ok := maybeCourse.(*[]*Course)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeCourse)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeCourse))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &courseR{}
		}
		args = append(args, object.ID)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &courseR{}
			}

			for _, a := range args {
				if queries.Equal(a, obj.ID) {
					continue Outer
				}
			}

			args = append(args, obj.ID)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`course_methods`),
		qm.WhereIn(`course_methods.course_id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load course_methods")
	}

	var resultSlice []*CourseMethod
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice course_methods")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on course_methods")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for course_methods")
	}

	if len(courseMethodAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.CourseMethods = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &courseMethodR{}
			}
			foreign.R.Course = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.ID, foreign.CourseID) {
				local.R.CourseMethods = append(local.R.CourseMethods, foreign)
				if foreign.R == nil {
					foreign.R = &courseMethodR{}
				}
				foreign.R.Course = local
				break
			}
		}
	}

	return nil
}

// LoadCourseRecommendedGrades allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (courseL) LoadCourseRecommendedGrades(ctx context.Context, e boil.ContextExecutor, singular bool, maybeCourse interface{}, mods queries.Applicator) error {
	var slice []*Course
	var object *Course

	if singular {
		var ok bool
		object, ok = maybeCourse.(*Course)
		if !ok {
			object = new(Course)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeCourse)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeCourse))
			}
		}
	} else {
		s, ok := maybeCourse.(*[]*Course)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeCourse)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeCourse))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &courseR{}
		}
		args = append(args, object.ID)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &courseR{}
			}

			for _, a := range args {
				if queries.Equal(a, obj.ID) {
					continue Outer
				}
			}

			args = append(args, obj.ID)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`course_recommended_grades`),
		qm.WhereIn(`course_recommended_grades.course_id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load course_recommended_grades")
	}

	var resultSlice []*CourseRecommendedGrade
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice course_recommended_grades")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on course_recommended_grades")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for course_recommended_grades")
	}

	if len(courseRecommendedGradeAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.CourseRecommendedGrades = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &courseRecommendedGradeR{}
			}
			foreign.R.Course = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.ID, foreign.CourseID) {
				local.R.CourseRecommendedGrades = append(local.R.CourseRecommendedGrades, foreign)
				if foreign.R == nil {
					foreign.R = &courseRecommendedGradeR{}
				}
				foreign.R.Course = local
				break
			}
		}
	}

	return nil
}

// LoadCourseSchedules allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (courseL) LoadCourseSchedules(ctx context.Context, e boil.ContextExecutor, singular bool, maybeCourse interface{}, mods queries.Applicator) error {
	var slice []*Course
	var object *Course

	if singular {
		var ok bool
		object, ok = maybeCourse.(*Course)
		if !ok {
			object = new(Course)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeCourse)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeCourse))
			}
		}
	} else {
		s, ok := maybeCourse.(*[]*Course)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeCourse)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeCourse))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &courseR{}
		}
		args = append(args, object.ID)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &courseR{}
			}

			for _, a := range args {
				if queries.Equal(a, obj.ID) {
					continue Outer
				}
			}

			args = append(args, obj.ID)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`course_schedules`),
		qm.WhereIn(`course_schedules.course_id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load course_schedules")
	}

	var resultSlice []*CourseSchedule
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice course_schedules")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on course_schedules")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for course_schedules")
	}

	if len(courseScheduleAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.CourseSchedules = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &courseScheduleR{}
			}
			foreign.R.Course = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.ID, foreign.CourseID) {
				local.R.CourseSchedules = append(local.R.CourseSchedules, foreign)
				if foreign.R == nil {
					foreign.R = &courseScheduleR{}
				}
				foreign.R.Course = local
				break
			}
		}
	}

	return nil
}

// AddCourseMethods adds the given related objects to the existing relationships
// of the course, optionally inserting them as new records.
// Appends related to o.R.CourseMethods.
// Sets related.R.Course appropriately.
func (o *Course) AddCourseMethods(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*CourseMethod) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.CourseID, o.ID)
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"course_methods\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"course_id"}),
				strmangle.WhereClause("\"", "\"", 2, courseMethodPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.CourseID, o.ID)
		}
	}

	if o.R == nil {
		o.R = &courseR{
			CourseMethods: related,
		}
	} else {
		o.R.CourseMethods = append(o.R.CourseMethods, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &courseMethodR{
				Course: o,
			}
		} else {
			rel.R.Course = o
		}
	}
	return nil
}

// SetCourseMethods removes all previously related items of the
// course replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.Course's CourseMethods accordingly.
// Replaces o.R.CourseMethods with related.
// Sets related.R.Course's CourseMethods accordingly.
func (o *Course) SetCourseMethods(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*CourseMethod) error {
	query := "update \"course_methods\" set \"course_id\" = null where \"course_id\" = $1"
	values := []interface{}{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.CourseMethods {
			queries.SetScanner(&rel.CourseID, nil)
			if rel.R == nil {
				continue
			}

			rel.R.Course = nil
		}
		o.R.CourseMethods = nil
	}

	return o.AddCourseMethods(ctx, exec, insert, related...)
}

// RemoveCourseMethods relationships from objects passed in.
// Removes related items from R.CourseMethods (uses pointer comparison, removal does not keep order)
// Sets related.R.Course.
func (o *Course) RemoveCourseMethods(ctx context.Context, exec boil.ContextExecutor, related ...*CourseMethod) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.CourseID, nil)
		if rel.R != nil {
			rel.R.Course = nil
		}
		if _, err = rel.Update(ctx, exec, boil.Whitelist("course_id")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.CourseMethods {
			if rel != ri {
				continue
			}

			ln := len(o.R.CourseMethods)
			if ln > 1 && i < ln-1 {
				o.R.CourseMethods[i] = o.R.CourseMethods[ln-1]
			}
			o.R.CourseMethods = o.R.CourseMethods[:ln-1]
			break
		}
	}

	return nil
}

// AddCourseRecommendedGrades adds the given related objects to the existing relationships
// of the course, optionally inserting them as new records.
// Appends related to o.R.CourseRecommendedGrades.
// Sets related.R.Course appropriately.
func (o *Course) AddCourseRecommendedGrades(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*CourseRecommendedGrade) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.CourseID, o.ID)
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"course_recommended_grades\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"course_id"}),
				strmangle.WhereClause("\"", "\"", 2, courseRecommendedGradePrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.CourseID, o.ID)
		}
	}

	if o.R == nil {
		o.R = &courseR{
			CourseRecommendedGrades: related,
		}
	} else {
		o.R.CourseRecommendedGrades = append(o.R.CourseRecommendedGrades, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &courseRecommendedGradeR{
				Course: o,
			}
		} else {
			rel.R.Course = o
		}
	}
	return nil
}

// SetCourseRecommendedGrades removes all previously related items of the
// course replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.Course's CourseRecommendedGrades accordingly.
// Replaces o.R.CourseRecommendedGrades with related.
// Sets related.R.Course's CourseRecommendedGrades accordingly.
func (o *Course) SetCourseRecommendedGrades(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*CourseRecommendedGrade) error {
	query := "update \"course_recommended_grades\" set \"course_id\" = null where \"course_id\" = $1"
	values := []interface{}{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.CourseRecommendedGrades {
			queries.SetScanner(&rel.CourseID, nil)
			if rel.R == nil {
				continue
			}

			rel.R.Course = nil
		}
		o.R.CourseRecommendedGrades = nil
	}

	return o.AddCourseRecommendedGrades(ctx, exec, insert, related...)
}

// RemoveCourseRecommendedGrades relationships from objects passed in.
// Removes related items from R.CourseRecommendedGrades (uses pointer comparison, removal does not keep order)
// Sets related.R.Course.
func (o *Course) RemoveCourseRecommendedGrades(ctx context.Context, exec boil.ContextExecutor, related ...*CourseRecommendedGrade) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.CourseID, nil)
		if rel.R != nil {
			rel.R.Course = nil
		}
		if _, err = rel.Update(ctx, exec, boil.Whitelist("course_id")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.CourseRecommendedGrades {
			if rel != ri {
				continue
			}

			ln := len(o.R.CourseRecommendedGrades)
			if ln > 1 && i < ln-1 {
				o.R.CourseRecommendedGrades[i] = o.R.CourseRecommendedGrades[ln-1]
			}
			o.R.CourseRecommendedGrades = o.R.CourseRecommendedGrades[:ln-1]
			break
		}
	}

	return nil
}

// AddCourseSchedules adds the given related objects to the existing relationships
// of the course, optionally inserting them as new records.
// Appends related to o.R.CourseSchedules.
// Sets related.R.Course appropriately.
func (o *Course) AddCourseSchedules(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*CourseSchedule) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.CourseID, o.ID)
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"course_schedules\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"course_id"}),
				strmangle.WhereClause("\"", "\"", 2, courseSchedulePrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.CourseID, o.ID)
		}
	}

	if o.R == nil {
		o.R = &courseR{
			CourseSchedules: related,
		}
	} else {
		o.R.CourseSchedules = append(o.R.CourseSchedules, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &courseScheduleR{
				Course: o,
			}
		} else {
			rel.R.Course = o
		}
	}
	return nil
}

// SetCourseSchedules removes all previously related items of the
// course replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.Course's CourseSchedules accordingly.
// Replaces o.R.CourseSchedules with related.
// Sets related.R.Course's CourseSchedules accordingly.
func (o *Course) SetCourseSchedules(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*CourseSchedule) error {
	query := "update \"course_schedules\" set \"course_id\" = null where \"course_id\" = $1"
	values := []interface{}{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.CourseSchedules {
			queries.SetScanner(&rel.CourseID, nil)
			if rel.R == nil {
				continue
			}

			rel.R.Course = nil
		}
		o.R.CourseSchedules = nil
	}

	return o.AddCourseSchedules(ctx, exec, insert, related...)
}

// RemoveCourseSchedules relationships from objects passed in.
// Removes related items from R.CourseSchedules (uses pointer comparison, removal does not keep order)
// Sets related.R.Course.
func (o *Course) RemoveCourseSchedules(ctx context.Context, exec boil.ContextExecutor, related ...*CourseSchedule) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.CourseID, nil)
		if rel.R != nil {
			rel.R.Course = nil
		}
		if _, err = rel.Update(ctx, exec, boil.Whitelist("course_id")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.CourseSchedules {
			if rel != ri {
				continue
			}

			ln := len(o.R.CourseSchedules)
			if ln > 1 && i < ln-1 {
				o.R.CourseSchedules[i] = o.R.CourseSchedules[ln-1]
			}
			o.R.CourseSchedules = o.R.CourseSchedules[:ln-1]
			break
		}
	}

	return nil
}

// Courses retrieves all the records using an executor.
func Courses(mods ...qm.QueryMod) courseQuery {
	mods = append(mods, qm.From("\"courses\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"courses\".*"})
	}

	return courseQuery{q}
}

// FindCourse retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindCourse(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*Course, error) {
	courseObj := &Course{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"courses\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, courseObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbmodel: unable to select from courses")
	}

	if err = courseObj.doAfterSelectHooks(ctx, exec); err != nil {
		return courseObj, err
	}

	return courseObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Course) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("dbmodel: no courses provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(courseColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	courseInsertCacheMut.RLock()
	cache, cached := courseInsertCache[key]
	courseInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			courseAllColumns,
			courseColumnsWithDefault,
			courseColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(courseType, courseMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(courseType, courseMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"courses\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"courses\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "dbmodel: unable to insert into courses")
	}

	if !cached {
		courseInsertCacheMut.Lock()
		courseInsertCache[key] = cache
		courseInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the Course.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Course) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	courseUpdateCacheMut.RLock()
	cache, cached := courseUpdateCache[key]
	courseUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			courseAllColumns,
			coursePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("dbmodel: unable to update courses, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"courses\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, coursePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(courseType, courseMapping, append(wl, coursePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodel: unable to update courses row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodel: failed to get rows affected by update for courses")
	}

	if !cached {
		courseUpdateCacheMut.Lock()
		courseUpdateCache[key] = cache
		courseUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q courseQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodel: unable to update all for courses")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodel: unable to retrieve rows affected for courses")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o CourseSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("dbmodel: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), coursePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"courses\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, coursePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodel: unable to update all in course slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodel: unable to retrieve rows affected all in update all course")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Course) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("dbmodel: no courses provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(courseColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	courseUpsertCacheMut.RLock()
	cache, cached := courseUpsertCache[key]
	courseUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			courseAllColumns,
			courseColumnsWithDefault,
			courseColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			courseAllColumns,
			coursePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("dbmodel: unable to upsert courses, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(coursePrimaryKeyColumns))
			copy(conflict, coursePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"courses\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(courseType, courseMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(courseType, courseMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "dbmodel: unable to upsert courses")
	}

	if !cached {
		courseUpsertCacheMut.Lock()
		courseUpsertCache[key] = cache
		courseUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single Course record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Course) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("dbmodel: no Course provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), coursePrimaryKeyMapping)
	sql := "DELETE FROM \"courses\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodel: unable to delete from courses")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodel: failed to get rows affected by delete for courses")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q courseQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("dbmodel: no courseQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodel: unable to delete all from courses")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodel: failed to get rows affected by deleteall for courses")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o CourseSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(courseBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), coursePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"courses\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, coursePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodel: unable to delete all from course slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodel: failed to get rows affected by deleteall for courses")
	}

	if len(courseAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Course) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindCourse(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *CourseSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := CourseSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), coursePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"courses\".* FROM \"courses\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, coursePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "dbmodel: unable to reload all in CourseSlice")
	}

	*o = slice

	return nil
}

// CourseExists checks if the Course row exists.
func CourseExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"courses\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "dbmodel: unable to check if courses exists")
	}

	return exists, nil
}

// Exists checks if the Course row exists.
func (o *Course) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return CourseExists(ctx, exec, o.ID)
}
