// Code generated by codegen/error/generate.py; DO NOT EDIT.

package schoolcalendarerr

import "github.com/twin-te/twinte-back/apperr"

const (
	CodeModuleNotFound apperr.Code = "schoolcalendar.ModuleNotFound"
)
