// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        (unknown)
// source: announcement/v1/service.proto

package announcementv1

import (
	sharedpb "github.com/twin-te/twinte-back/handler/api/rpcgen/sharedpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAnnouncementsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAnnouncementsRequest) Reset() {
	*x = GetAnnouncementsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_announcement_v1_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAnnouncementsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnnouncementsRequest) ProtoMessage() {}

func (x *GetAnnouncementsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_announcement_v1_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnnouncementsRequest.ProtoReflect.Descriptor instead.
func (*GetAnnouncementsRequest) Descriptor() ([]byte, []int) {
	return file_announcement_v1_service_proto_rawDescGZIP(), []int{0}
}

type GetAnnouncementsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Announcements []*Announcement `protobuf:"bytes,1,rep,name=announcements,proto3" json:"announcements,omitempty"`
}

func (x *GetAnnouncementsResponse) Reset() {
	*x = GetAnnouncementsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_announcement_v1_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAnnouncementsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnnouncementsResponse) ProtoMessage() {}

func (x *GetAnnouncementsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_announcement_v1_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnnouncementsResponse.ProtoReflect.Descriptor instead.
func (*GetAnnouncementsResponse) Descriptor() ([]byte, []int) {
	return file_announcement_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetAnnouncementsResponse) GetAnnouncements() []*Announcement {
	if x != nil {
		return x.Announcements
	}
	return nil
}

type GetReadFlagsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []*sharedpb.UUID `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
}

func (x *GetReadFlagsRequest) Reset() {
	*x = GetReadFlagsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_announcement_v1_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReadFlagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReadFlagsRequest) ProtoMessage() {}

func (x *GetReadFlagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_announcement_v1_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReadFlagsRequest.ProtoReflect.Descriptor instead.
func (*GetReadFlagsRequest) Descriptor() ([]byte, []int) {
	return file_announcement_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetReadFlagsRequest) GetIds() []*sharedpb.UUID {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetReadFlagsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReadFlags []bool `protobuf:"varint,1,rep,packed,name=read_flags,json=readFlags,proto3" json:"read_flags,omitempty"`
}

func (x *GetReadFlagsResponse) Reset() {
	*x = GetReadFlagsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_announcement_v1_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReadFlagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReadFlagsResponse) ProtoMessage() {}

func (x *GetReadFlagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_announcement_v1_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReadFlagsResponse.ProtoReflect.Descriptor instead.
func (*GetReadFlagsResponse) Descriptor() ([]byte, []int) {
	return file_announcement_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetReadFlagsResponse) GetReadFlags() []bool {
	if x != nil {
		return x.ReadFlags
	}
	return nil
}

type UpdateReadFlagRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       *sharedpb.UUID `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ReadFlag bool           `protobuf:"varint,2,opt,name=read_flag,json=readFlag,proto3" json:"read_flag,omitempty"`
}

func (x *UpdateReadFlagRequest) Reset() {
	*x = UpdateReadFlagRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_announcement_v1_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateReadFlagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReadFlagRequest) ProtoMessage() {}

func (x *UpdateReadFlagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_announcement_v1_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReadFlagRequest.ProtoReflect.Descriptor instead.
func (*UpdateReadFlagRequest) Descriptor() ([]byte, []int) {
	return file_announcement_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateReadFlagRequest) GetId() *sharedpb.UUID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *UpdateReadFlagRequest) GetReadFlag() bool {
	if x != nil {
		return x.ReadFlag
	}
	return false
}

type UpdateReadFlagResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateReadFlagResponse) Reset() {
	*x = UpdateReadFlagResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_announcement_v1_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateReadFlagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReadFlagResponse) ProtoMessage() {}

func (x *UpdateReadFlagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_announcement_v1_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReadFlagResponse.ProtoReflect.Descriptor instead.
func (*UpdateReadFlagResponse) Descriptor() ([]byte, []int) {
	return file_announcement_v1_service_proto_rawDescGZIP(), []int{5}
}

var File_announcement_v1_service_proto protoreflect.FileDescriptor

var file_announcement_v1_service_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x61, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x76,
	0x31, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0f, 0x61, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31,
	0x1a, 0x1a, 0x61, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x76,
	0x31, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x73, 0x68,
	0x61, 0x72, 0x65, 0x64, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x19, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x5f, 0x0a, 0x18, 0x47, 0x65,
	0x74, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a, 0x0d, 0x61, 0x6e, 0x6e, 0x6f, 0x75, 0x6e,
	0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e,
	0x61, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e,
	0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x0d, 0x61, 0x6e,
	0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x35, 0x0a, 0x13, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x61, 0x64, 0x46, 0x6c, 0x61, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1e, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x55, 0x55, 0x49, 0x44, 0x52, 0x03, 0x69,
	0x64, 0x73, 0x22, 0x35, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x52, 0x65, 0x61, 0x64, 0x46, 0x6c, 0x61,
	0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65,
	0x61, 0x64, 0x5f, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x08, 0x52, 0x09,
	0x72, 0x65, 0x61, 0x64, 0x46, 0x6c, 0x61, 0x67, 0x73, 0x22, 0x52, 0x0a, 0x15, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x61, 0x64, 0x46, 0x6c, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1c, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x55, 0x55, 0x49, 0x44, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x61, 0x64, 0x5f, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x08, 0x72, 0x65, 0x61, 0x64, 0x46, 0x6c, 0x61, 0x67, 0x22, 0x18, 0x0a,
	0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x61, 0x64, 0x46, 0x6c, 0x61, 0x67, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xc8, 0x02, 0x0a, 0x13, 0x41, 0x6e, 0x6e, 0x6f,
	0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x6c, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x73, 0x12, 0x28, 0x2e, 0x61, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e,
	0x61, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x03, 0x90, 0x02, 0x01, 0x12, 0x60, 0x0a,
	0x0c, 0x47, 0x65, 0x74, 0x52, 0x65, 0x61, 0x64, 0x46, 0x6c, 0x61, 0x67, 0x73, 0x12, 0x24, 0x2e,
	0x61, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x61, 0x64, 0x46, 0x6c, 0x61, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x61, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x61, 0x64, 0x46, 0x6c, 0x61,
	0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x03, 0x90, 0x02, 0x01, 0x12,
	0x61, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x61, 0x64, 0x46, 0x6c, 0x61,
	0x67, 0x12, 0x26, 0x2e, 0x61, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x61, 0x64, 0x46, 0x6c,
	0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x61, 0x6e, 0x6e, 0x6f,
	0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x61, 0x64, 0x46, 0x6c, 0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x52, 0x5a, 0x50, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x74, 0x77, 0x69, 0x6e, 0x2d, 0x74, 0x65, 0x2f, 0x74, 0x77, 0x69, 0x6e, 0x74, 0x65, 0x2d,
	0x62, 0x61, 0x63, 0x6b, 0x2f, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x72, 0x70, 0x63, 0x67, 0x65, 0x6e, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x76, 0x31, 0x3b, 0x61, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_announcement_v1_service_proto_rawDescOnce sync.Once
	file_announcement_v1_service_proto_rawDescData = file_announcement_v1_service_proto_rawDesc
)

func file_announcement_v1_service_proto_rawDescGZIP() []byte {
	file_announcement_v1_service_proto_rawDescOnce.Do(func() {
		file_announcement_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_announcement_v1_service_proto_rawDescData)
	})
	return file_announcement_v1_service_proto_rawDescData
}

var file_announcement_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_announcement_v1_service_proto_goTypes = []interface{}{
	(*GetAnnouncementsRequest)(nil),  // 0: announcement.v1.GetAnnouncementsRequest
	(*GetAnnouncementsResponse)(nil), // 1: announcement.v1.GetAnnouncementsResponse
	(*GetReadFlagsRequest)(nil),      // 2: announcement.v1.GetReadFlagsRequest
	(*GetReadFlagsResponse)(nil),     // 3: announcement.v1.GetReadFlagsResponse
	(*UpdateReadFlagRequest)(nil),    // 4: announcement.v1.UpdateReadFlagRequest
	(*UpdateReadFlagResponse)(nil),   // 5: announcement.v1.UpdateReadFlagResponse
	(*Announcement)(nil),             // 6: announcement.v1.Announcement
	(*sharedpb.UUID)(nil),            // 7: shared.UUID
}
var file_announcement_v1_service_proto_depIdxs = []int32{
	6, // 0: announcement.v1.GetAnnouncementsResponse.announcements:type_name -> announcement.v1.Announcement
	7, // 1: announcement.v1.GetReadFlagsRequest.ids:type_name -> shared.UUID
	7, // 2: announcement.v1.UpdateReadFlagRequest.id:type_name -> shared.UUID
	0, // 3: announcement.v1.AnnouncementService.GetAnnouncements:input_type -> announcement.v1.GetAnnouncementsRequest
	2, // 4: announcement.v1.AnnouncementService.GetReadFlags:input_type -> announcement.v1.GetReadFlagsRequest
	4, // 5: announcement.v1.AnnouncementService.UpdateReadFlag:input_type -> announcement.v1.UpdateReadFlagRequest
	1, // 6: announcement.v1.AnnouncementService.GetAnnouncements:output_type -> announcement.v1.GetAnnouncementsResponse
	3, // 7: announcement.v1.AnnouncementService.GetReadFlags:output_type -> announcement.v1.GetReadFlagsResponse
	5, // 8: announcement.v1.AnnouncementService.UpdateReadFlag:output_type -> announcement.v1.UpdateReadFlagResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_announcement_v1_service_proto_init() }
func file_announcement_v1_service_proto_init() {
	if File_announcement_v1_service_proto != nil {
		return
	}
	file_announcement_v1_type_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_announcement_v1_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAnnouncementsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_announcement_v1_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAnnouncementsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_announcement_v1_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReadFlagsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_announcement_v1_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReadFlagsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_announcement_v1_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateReadFlagRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_announcement_v1_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateReadFlagResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_announcement_v1_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_announcement_v1_service_proto_goTypes,
		DependencyIndexes: file_announcement_v1_service_proto_depIdxs,
		MessageInfos:      file_announcement_v1_service_proto_msgTypes,
	}.Build()
	File_announcement_v1_service_proto = out.File
	file_announcement_v1_service_proto_rawDesc = nil
	file_announcement_v1_service_proto_goTypes = nil
	file_announcement_v1_service_proto_depIdxs = nil
}
