// Code generated by "stringer -type=Module -trimprefix=Module -output=module_string.gen.go"; DO NOT EDIT.

package schoolcalendardomain

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ModuleSpringA-1]
	_ = x[ModuleSpringB-2]
	_ = x[ModuleSpringC-3]
	_ = x[ModuleSummerVacation-4]
	_ = x[ModuleFallA-5]
	_ = x[ModuleFallB-6]
	_ = x[ModuleWinterVacation-7]
	_ = x[ModuleFallC-8]
	_ = x[ModuleSpringVacation-9]
}

const _Module_name = "SpringASpringBSpringCSummerVacationFallAFallBWinterVacationFallCSpringVacation"

var _Module_index = [...]uint8{0, 7, 14, 21, 35, 40, 45, 59, 64, 78}

func (i Module) String() string {
	i -= 1
	if i < 0 || i >= Module(len(_Module_index)-1) {
		return "Module(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Module_name[_Module_index[i]:_Module_index[i+1]]
}
