// Code generated by "stringer -type=Weekday -trimprefix=Weekday -output=weekday_string.gen.go"; DO NOT EDIT.

package schoolcalendardomain

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WeekdaySunday-1]
	_ = x[WeekdayMonday-2]
	_ = x[WeekdayTuesday-3]
	_ = x[WeekdayWednesday-4]
	_ = x[WeekdayThursday-5]
	_ = x[WeekdayFriday-6]
	_ = x[WeekdaySaturday-7]
}

const _Weekday_name = "SundayMondayTuesdayWednesdayThursdayFridaySaturday"

var _Weekday_index = [...]uint8{0, 6, 12, 19, 28, 36, 42, 50}

func (i Weekday) String() string {
	i -= 1
	if i < 0 || i >= Weekday(len(_Weekday_index)-1) {
		return "Weekday(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Weekday_name[_Weekday_index[i]:_Weekday_index[i+1]]
}
