// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        (unknown)
// source: shared/option.proto

package sharedpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Authentication int32

const (
	Authentication_AUTHENTICATION_UNSPECIFIED Authentication = 0
	Authentication_NOT_REQURED                Authentication = 1
	Authentication_OPTIONAL                   Authentication = 2
	Authentication_REQURED                    Authentication = 3
)

// Enum value maps for Authentication.
var (
	Authentication_name = map[int32]string{
		0: "AUTHENTICATION_UNSPECIFIED",
		1: "NOT_REQURED",
		2: "OPTIONAL",
		3: "REQURED",
	}
	Authentication_value = map[string]int32{
		"AUTHENTICATION_UNSPECIFIED": 0,
		"NOT_REQURED":                1,
		"OPTIONAL":                   2,
		"REQURED":                    3,
	}
)

func (x Authentication) Enum() *Authentication {
	p := new(Authentication)
	*p = x
	return p
}

func (x Authentication) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Authentication) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_option_proto_enumTypes[0].Descriptor()
}

func (Authentication) Type() protoreflect.EnumType {
	return &file_shared_option_proto_enumTypes[0]
}

func (x Authentication) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Authentication.Descriptor instead.
func (Authentication) EnumDescriptor() ([]byte, []int) {
	return file_shared_option_proto_rawDescGZIP(), []int{0}
}

type TwinteMethodOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Authentication Authentication `protobuf:"varint,1,opt,name=authentication,proto3,enum=shared.Authentication" json:"authentication,omitempty"`
	ErrorCodes     []string       `protobuf:"bytes,2,rep,name=error_codes,json=errorCodes,proto3" json:"error_codes,omitempty"`
}

func (x *TwinteMethodOptions) Reset() {
	*x = TwinteMethodOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_option_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TwinteMethodOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwinteMethodOptions) ProtoMessage() {}

func (x *TwinteMethodOptions) ProtoReflect() protoreflect.Message {
	mi := &file_shared_option_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwinteMethodOptions.ProtoReflect.Descriptor instead.
func (*TwinteMethodOptions) Descriptor() ([]byte, []int) {
	return file_shared_option_proto_rawDescGZIP(), []int{0}
}

func (x *TwinteMethodOptions) GetAuthentication() Authentication {
	if x != nil {
		return x.Authentication
	}
	return Authentication_AUTHENTICATION_UNSPECIFIED
}

func (x *TwinteMethodOptions) GetErrorCodes() []string {
	if x != nil {
		return x.ErrorCodes
	}
	return nil
}

var file_shared_option_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*TwinteMethodOptions)(nil),
		Field:         50000,
		Name:          "shared.twinte",
		Tag:           "bytes,50000,opt,name=twinte",
		Filename:      "shared/option.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional shared.TwinteMethodOptions twinte = 50000;
	E_Twinte = &file_shared_option_proto_extTypes[0]
)

var File_shared_option_proto protoreflect.FileDescriptor

var file_shared_option_proto_rawDesc = []byte{
	0x0a, 0x13, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x1a, 0x20, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x76, 0x0a, 0x13, 0x54, 0x77, 0x69, 0x6e, 0x74, 0x65, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x3e, 0x0a, 0x0e, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e,
	0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16,
	0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0e, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f,
	0x63, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x73, 0x2a, 0x5c, 0x0a, 0x0e, 0x41, 0x75, 0x74, 0x68, 0x65,
	0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x1a, 0x41, 0x55, 0x54,
	0x48, 0x45, 0x4e, 0x54, 0x49, 0x43, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x55, 0x4e, 0x53, 0x50,
	0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x4e, 0x4f, 0x54,
	0x5f, 0x52, 0x45, 0x51, 0x55, 0x52, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x4f, 0x50,
	0x54, 0x49, 0x4f, 0x4e, 0x41, 0x4c, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x45, 0x51, 0x55,
	0x52, 0x45, 0x44, 0x10, 0x03, 0x3a, 0x55, 0x0a, 0x06, 0x74, 0x77, 0x69, 0x6e, 0x74, 0x65, 0x12,
	0x1e, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0xd0, 0x86, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64,
	0x2e, 0x54, 0x77, 0x69, 0x6e, 0x74, 0x65, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x52, 0x06, 0x74, 0x77, 0x69, 0x6e, 0x74, 0x65, 0x42, 0x3c, 0x5a, 0x3a,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x77, 0x69, 0x6e, 0x2d,
	0x74, 0x65, 0x2f, 0x74, 0x77, 0x69, 0x6e, 0x74, 0x65, 0x2d, 0x62, 0x61, 0x63, 0x6b, 0x2f, 0x68,
	0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x70, 0x63, 0x67, 0x65,
	0x6e, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_shared_option_proto_rawDescOnce sync.Once
	file_shared_option_proto_rawDescData = file_shared_option_proto_rawDesc
)

func file_shared_option_proto_rawDescGZIP() []byte {
	file_shared_option_proto_rawDescOnce.Do(func() {
		file_shared_option_proto_rawDescData = protoimpl.X.CompressGZIP(file_shared_option_proto_rawDescData)
	})
	return file_shared_option_proto_rawDescData
}

var file_shared_option_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_shared_option_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_shared_option_proto_goTypes = []interface{}{
	(Authentication)(0),                // 0: shared.Authentication
	(*TwinteMethodOptions)(nil),        // 1: shared.TwinteMethodOptions
	(*descriptorpb.MethodOptions)(nil), // 2: google.protobuf.MethodOptions
}
var file_shared_option_proto_depIdxs = []int32{
	0, // 0: shared.TwinteMethodOptions.authentication:type_name -> shared.Authentication
	2, // 1: shared.twinte:extendee -> google.protobuf.MethodOptions
	1, // 2: shared.twinte:type_name -> shared.TwinteMethodOptions
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	2, // [2:3] is the sub-list for extension type_name
	1, // [1:2] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_shared_option_proto_init() }
func file_shared_option_proto_init() {
	if File_shared_option_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_shared_option_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TwinteMethodOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_shared_option_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_shared_option_proto_goTypes,
		DependencyIndexes: file_shared_option_proto_depIdxs,
		EnumInfos:         file_shared_option_proto_enumTypes,
		MessageInfos:      file_shared_option_proto_msgTypes,
		ExtensionInfos:    file_shared_option_proto_extTypes,
	}.Build()
	File_shared_option_proto = out.File
	file_shared_option_proto_rawDesc = nil
	file_shared_option_proto_goTypes = nil
	file_shared_option_proto_depIdxs = nil
}
