// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        (unknown)
// source: shared/type.proto

package sharedpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Weekday int32

const (
	Weekday_WEEKDAY_UNSPECIFIED Weekday = 0
	Weekday_WEEKDAY_SUNDAY      Weekday = 1
	Weekday_WEEKDAY_MONDAY      Weekday = 2
	Weekday_WEEKDAY_TUESDAY     Weekday = 3
	Weekday_WEEKDAY_WEDNESDAY   Weekday = 4
	Weekday_WEEKDAY_THURSDAY    Weekday = 5
	Weekday_WEEKDAY_FRIDAY      Weekday = 6
	Weekday_WEEKDAY_SATURDAY    Weekday = 7
)

// Enum value maps for Weekday.
var (
	Weekday_name = map[int32]string{
		0: "WEEKDAY_UNSPECIFIED",
		1: "WEEKDAY_SUNDAY",
		2: "WEEKDAY_MONDAY",
		3: "WEEKDAY_TUESDAY",
		4: "WEEKDAY_WEDNESDAY",
		5: "WEEKDAY_THURSDAY",
		6: "WEEKDAY_FRIDAY",
		7: "WEEKDAY_SATURDAY",
	}
	Weekday_value = map[string]int32{
		"WEEKDAY_UNSPECIFIED": 0,
		"WEEKDAY_SUNDAY":      1,
		"WEEKDAY_MONDAY":      2,
		"WEEKDAY_TUESDAY":     3,
		"WEEKDAY_WEDNESDAY":   4,
		"WEEKDAY_THURSDAY":    5,
		"WEEKDAY_FRIDAY":      6,
		"WEEKDAY_SATURDAY":    7,
	}
)

func (x Weekday) Enum() *Weekday {
	p := new(Weekday)
	*p = x
	return p
}

func (x Weekday) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Weekday) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_type_proto_enumTypes[0].Descriptor()
}

func (Weekday) Type() protoreflect.EnumType {
	return &file_shared_type_proto_enumTypes[0]
}

func (x Weekday) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Weekday.Descriptor instead.
func (Weekday) EnumDescriptor() ([]byte, []int) {
	return file_shared_type_proto_rawDescGZIP(), []int{0}
}

type AcademicYear struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int32 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *AcademicYear) Reset() {
	*x = AcademicYear{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_type_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcademicYear) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcademicYear) ProtoMessage() {}

func (x *AcademicYear) ProtoReflect() protoreflect.Message {
	mi := &file_shared_type_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcademicYear.ProtoReflect.Descriptor instead.
func (*AcademicYear) Descriptor() ([]byte, []int) {
	return file_shared_type_proto_rawDescGZIP(), []int{0}
}

func (x *AcademicYear) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type UUID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *UUID) Reset() {
	*x = UUID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_type_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UUID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UUID) ProtoMessage() {}

func (x *UUID) ProtoReflect() protoreflect.Message {
	mi := &file_shared_type_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UUID.ProtoReflect.Descriptor instead.
func (*UUID) Descriptor() ([]byte, []int) {
	return file_shared_type_proto_rawDescGZIP(), []int{1}
}

func (x *UUID) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type UUIDList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []*UUID `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *UUIDList) Reset() {
	*x = UUIDList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_type_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UUIDList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UUIDList) ProtoMessage() {}

func (x *UUIDList) ProtoReflect() protoreflect.Message {
	mi := &file_shared_type_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UUIDList.ProtoReflect.Descriptor instead.
func (*UUIDList) Descriptor() ([]byte, []int) {
	return file_shared_type_proto_rawDescGZIP(), []int{2}
}

func (x *UUIDList) GetValues() []*UUID {
	if x != nil {
		return x.Values
	}
	return nil
}

// e.g. 2006-01-02
type RFC3339FullDate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *RFC3339FullDate) Reset() {
	*x = RFC3339FullDate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_type_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RFC3339FullDate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RFC3339FullDate) ProtoMessage() {}

func (x *RFC3339FullDate) ProtoReflect() protoreflect.Message {
	mi := &file_shared_type_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RFC3339FullDate.ProtoReflect.Descriptor instead.
func (*RFC3339FullDate) Descriptor() ([]byte, []int) {
	return file_shared_type_proto_rawDescGZIP(), []int{3}
}

func (x *RFC3339FullDate) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// e.g. 2006-01-02T15:04:05+09:00
type RFC3339DateTime struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *RFC3339DateTime) Reset() {
	*x = RFC3339DateTime{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_type_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RFC3339DateTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RFC3339DateTime) ProtoMessage() {}

func (x *RFC3339DateTime) ProtoReflect() protoreflect.Message {
	mi := &file_shared_type_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RFC3339DateTime.ProtoReflect.Descriptor instead.
func (*RFC3339DateTime) Descriptor() ([]byte, []int) {
	return file_shared_type_proto_rawDescGZIP(), []int{4}
}

func (x *RFC3339DateTime) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_shared_type_proto protoreflect.FileDescriptor

var file_shared_type_proto_rawDesc = []byte{
	0x0a, 0x11, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x06, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x22, 0x24, 0x0a, 0x0c, 0x41,
	0x63, 0x61, 0x64, 0x65, 0x6d, 0x69, 0x63, 0x59, 0x65, 0x61, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x22, 0x1c, 0x0a, 0x04, 0x55, 0x55, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22,
	0x30, 0x0a, 0x08, 0x55, 0x55, 0x49, 0x44, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x06, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x73, 0x68,
	0x61, 0x72, 0x65, 0x64, 0x2e, 0x55, 0x55, 0x49, 0x44, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x73, 0x22, 0x27, 0x0a, 0x0f, 0x52, 0x46, 0x43, 0x33, 0x33, 0x33, 0x39, 0x46, 0x75, 0x6c, 0x6c,
	0x44, 0x61, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x27, 0x0a, 0x0f, 0x52, 0x46,
	0x43, 0x33, 0x33, 0x33, 0x39, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x2a, 0xb6, 0x01, 0x0a, 0x07, 0x57, 0x65, 0x65, 0x6b, 0x64, 0x61, 0x79, 0x12,
	0x17, 0x0a, 0x13, 0x57, 0x45, 0x45, 0x4b, 0x44, 0x41, 0x59, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45,
	0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x57, 0x45, 0x45, 0x4b,
	0x44, 0x41, 0x59, 0x5f, 0x53, 0x55, 0x4e, 0x44, 0x41, 0x59, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e,
	0x57, 0x45, 0x45, 0x4b, 0x44, 0x41, 0x59, 0x5f, 0x4d, 0x4f, 0x4e, 0x44, 0x41, 0x59, 0x10, 0x02,
	0x12, 0x13, 0x0a, 0x0f, 0x57, 0x45, 0x45, 0x4b, 0x44, 0x41, 0x59, 0x5f, 0x54, 0x55, 0x45, 0x53,
	0x44, 0x41, 0x59, 0x10, 0x03, 0x12, 0x15, 0x0a, 0x11, 0x57, 0x45, 0x45, 0x4b, 0x44, 0x41, 0x59,
	0x5f, 0x57, 0x45, 0x44, 0x4e, 0x45, 0x53, 0x44, 0x41, 0x59, 0x10, 0x04, 0x12, 0x14, 0x0a, 0x10,
	0x57, 0x45, 0x45, 0x4b, 0x44, 0x41, 0x59, 0x5f, 0x54, 0x48, 0x55, 0x52, 0x53, 0x44, 0x41, 0x59,
	0x10, 0x05, 0x12, 0x12, 0x0a, 0x0e, 0x57, 0x45, 0x45, 0x4b, 0x44, 0x41, 0x59, 0x5f, 0x46, 0x52,
	0x49, 0x44, 0x41, 0x59, 0x10, 0x06, 0x12, 0x14, 0x0a, 0x10, 0x57, 0x45, 0x45, 0x4b, 0x44, 0x41,
	0x59, 0x5f, 0x53, 0x41, 0x54, 0x55, 0x52, 0x44, 0x41, 0x59, 0x10, 0x07, 0x42, 0x3c, 0x5a, 0x3a,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x77, 0x69, 0x6e, 0x2d,
	0x74, 0x65, 0x2f, 0x74, 0x77, 0x69, 0x6e, 0x74, 0x65, 0x2d, 0x62, 0x61, 0x63, 0x6b, 0x2f, 0x68,
	0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x70, 0x63, 0x67, 0x65,
	0x6e, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_shared_type_proto_rawDescOnce sync.Once
	file_shared_type_proto_rawDescData = file_shared_type_proto_rawDesc
)

func file_shared_type_proto_rawDescGZIP() []byte {
	file_shared_type_proto_rawDescOnce.Do(func() {
		file_shared_type_proto_rawDescData = protoimpl.X.CompressGZIP(file_shared_type_proto_rawDescData)
	})
	return file_shared_type_proto_rawDescData
}

var file_shared_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_shared_type_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_shared_type_proto_goTypes = []interface{}{
	(Weekday)(0),            // 0: shared.Weekday
	(*AcademicYear)(nil),    // 1: shared.AcademicYear
	(*UUID)(nil),            // 2: shared.UUID
	(*UUIDList)(nil),        // 3: shared.UUIDList
	(*RFC3339FullDate)(nil), // 4: shared.RFC3339FullDate
	(*RFC3339DateTime)(nil), // 5: shared.RFC3339DateTime
}
var file_shared_type_proto_depIdxs = []int32{
	2, // 0: shared.UUIDList.values:type_name -> shared.UUID
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_shared_type_proto_init() }
func file_shared_type_proto_init() {
	if File_shared_type_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_shared_type_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcademicYear); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_type_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UUID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_type_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UUIDList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_type_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RFC3339FullDate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_type_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RFC3339DateTime); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_shared_type_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shared_type_proto_goTypes,
		DependencyIndexes: file_shared_type_proto_depIdxs,
		EnumInfos:         file_shared_type_proto_enumTypes,
		MessageInfos:      file_shared_type_proto_msgTypes,
	}.Build()
	File_shared_type_proto = out.File
	file_shared_type_proto_rawDesc = nil
	file_shared_type_proto_goTypes = nil
	file_shared_type_proto_depIdxs = nil
}
