// Code generated by codegen/idtype/generate.py; DO NOT EDIT.

package idtype

import "github.com/google/uuid"

type EventID uuid.UUID

func (id EventID) String() string {
	return uuid.UUID(id).String()
}

func (id EventID) IsZero() bool {
	return uuid.UUID(id) == uuid.Nil
}

func NewEventID() EventID {
	return EventID(uuid.New())
}

func NewEventIDFromString(s string) (EventID, error) {
	id, err := uuid.Parse(s)
	if err != nil {
		return EventID{}, err
	}
	return EventID(id), nil
}

type EventIDs []EventID

func (ids EventIDs) StringSlice() []string {
	ret := make([]string, 0, len(ids))
	for _, id := range ids {
		ret = append(ret, id.String())
	}
	return ret
}
