// Code generated by codegen/idtype/generate.py; DO NOT EDIT.

package idtype

type ModuleDetailID int

func (id ModuleDetailID) Int() int {
	return int(id)
}

func NewModuleDetailIDFromInt(i int) ModuleDetailID {
	return ModuleDetailID(i)
}
