// Code generated by codegen/idtype/generate.py; DO NOT EDIT.

package idtype

import "github.com/google/uuid"

type SessionID uuid.UUID

func (id SessionID) String() string {
	return uuid.UUID(id).String()
}

func (id SessionID) IsZero() bool {
	return uuid.UUID(id) == uuid.Nil
}

func NewSessionID() SessionID {
	return SessionID(uuid.New())
}

func NewSessionIDFromString(s string) (SessionID, error) {
	id, err := uuid.Parse(s)
	if err != nil {
		return SessionID{}, err
	}
	return SessionID(id), nil
}

type SessionIDs []SessionID

func (ids SessionIDs) StringSlice() []string {
	ret := make([]string, 0, len(ids))
	for _, id := range ids {
		ret = append(ret, id.String())
	}
	return ret
}
