// Code generated by codegen/idtype/generate.py; DO NOT EDIT.

package idtype

import "github.com/google/uuid"

type UserID uuid.UUID

func (id UserID) String() string {
	return uuid.UUID(id).String()
}

func (id UserID) IsZero() bool {
	return uuid.UUID(id) == uuid.Nil
}

func NewUserID() UserID {
	return UserID(uuid.New())
}

func NewUserIDFromString(s string) (UserID, error) {
	id, err := uuid.Parse(s)
	if err != nil {
		return UserID{}, err
	}
	return UserID(id), nil
}

type UserIDs []UserID

func (ids UserIDs) StringSlice() []string {
	ret := make([]string, 0, len(ids))
	for _, id := range ids {
		ret = append(ret, id.String())
	}
	return ret
}
