// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: announcement/v1/service.proto

package announcementv1connect

import (
	context "context"
	errors "errors"
	connect_go "github.com/bufbuild/connect-go"
	v1 "github.com/twin-te/twinte-back/api/rpcgen/announcement/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion1_7_0

const (
	// AnnouncementServiceName is the fully-qualified name of the AnnouncementService service.
	AnnouncementServiceName = "announcement.v1.AnnouncementService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AnnouncementServiceGetAnnouncementsProcedure is the fully-qualified name of the
	// AnnouncementService's GetAnnouncements RPC.
	AnnouncementServiceGetAnnouncementsProcedure = "/announcement.v1.AnnouncementService/GetAnnouncements"
	// AnnouncementServiceGetReadFlagsProcedure is the fully-qualified name of the AnnouncementService's
	// GetReadFlags RPC.
	AnnouncementServiceGetReadFlagsProcedure = "/announcement.v1.AnnouncementService/GetReadFlags"
	// AnnouncementServiceUpdateReadFlagProcedure is the fully-qualified name of the
	// AnnouncementService's UpdateReadFlag RPC.
	AnnouncementServiceUpdateReadFlagProcedure = "/announcement.v1.AnnouncementService/UpdateReadFlag"
)

// AnnouncementServiceClient is a client for the announcement.v1.AnnouncementService service.
type AnnouncementServiceClient interface {
	// PermissionPublic
	GetAnnouncements(context.Context, *connect_go.Request[v1.GetAnnouncementsRequest]) (*connect_go.Response[v1.GetAnnouncementsResponse], error)
	GetReadFlags(context.Context, *connect_go.Request[v1.GetReadFlagsRequest]) (*connect_go.Response[v1.GetReadFlagsResponse], error)
	UpdateReadFlag(context.Context, *connect_go.Request[v1.UpdateReadFlagRequest]) (*connect_go.Response[v1.UpdateReadFlagResponse], error)
}

// NewAnnouncementServiceClient constructs a client for the announcement.v1.AnnouncementService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAnnouncementServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) AnnouncementServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &announcementServiceClient{
		getAnnouncements: connect_go.NewClient[v1.GetAnnouncementsRequest, v1.GetAnnouncementsResponse](
			httpClient,
			baseURL+AnnouncementServiceGetAnnouncementsProcedure,
			connect_go.WithIdempotency(connect_go.IdempotencyNoSideEffects),
			connect_go.WithClientOptions(opts...),
		),
		getReadFlags: connect_go.NewClient[v1.GetReadFlagsRequest, v1.GetReadFlagsResponse](
			httpClient,
			baseURL+AnnouncementServiceGetReadFlagsProcedure,
			connect_go.WithIdempotency(connect_go.IdempotencyNoSideEffects),
			connect_go.WithClientOptions(opts...),
		),
		updateReadFlag: connect_go.NewClient[v1.UpdateReadFlagRequest, v1.UpdateReadFlagResponse](
			httpClient,
			baseURL+AnnouncementServiceUpdateReadFlagProcedure,
			opts...,
		),
	}
}

// announcementServiceClient implements AnnouncementServiceClient.
type announcementServiceClient struct {
	getAnnouncements *connect_go.Client[v1.GetAnnouncementsRequest, v1.GetAnnouncementsResponse]
	getReadFlags     *connect_go.Client[v1.GetReadFlagsRequest, v1.GetReadFlagsResponse]
	updateReadFlag   *connect_go.Client[v1.UpdateReadFlagRequest, v1.UpdateReadFlagResponse]
}

// GetAnnouncements calls announcement.v1.AnnouncementService.GetAnnouncements.
func (c *announcementServiceClient) GetAnnouncements(ctx context.Context, req *connect_go.Request[v1.GetAnnouncementsRequest]) (*connect_go.Response[v1.GetAnnouncementsResponse], error) {
	return c.getAnnouncements.CallUnary(ctx, req)
}

// GetReadFlags calls announcement.v1.AnnouncementService.GetReadFlags.
func (c *announcementServiceClient) GetReadFlags(ctx context.Context, req *connect_go.Request[v1.GetReadFlagsRequest]) (*connect_go.Response[v1.GetReadFlagsResponse], error) {
	return c.getReadFlags.CallUnary(ctx, req)
}

// UpdateReadFlag calls announcement.v1.AnnouncementService.UpdateReadFlag.
func (c *announcementServiceClient) UpdateReadFlag(ctx context.Context, req *connect_go.Request[v1.UpdateReadFlagRequest]) (*connect_go.Response[v1.UpdateReadFlagResponse], error) {
	return c.updateReadFlag.CallUnary(ctx, req)
}

// AnnouncementServiceHandler is an implementation of the announcement.v1.AnnouncementService
// service.
type AnnouncementServiceHandler interface {
	// PermissionPublic
	GetAnnouncements(context.Context, *connect_go.Request[v1.GetAnnouncementsRequest]) (*connect_go.Response[v1.GetAnnouncementsResponse], error)
	GetReadFlags(context.Context, *connect_go.Request[v1.GetReadFlagsRequest]) (*connect_go.Response[v1.GetReadFlagsResponse], error)
	UpdateReadFlag(context.Context, *connect_go.Request[v1.UpdateReadFlagRequest]) (*connect_go.Response[v1.UpdateReadFlagResponse], error)
}

// NewAnnouncementServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAnnouncementServiceHandler(svc AnnouncementServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	announcementServiceGetAnnouncementsHandler := connect_go.NewUnaryHandler(
		AnnouncementServiceGetAnnouncementsProcedure,
		svc.GetAnnouncements,
		connect_go.WithIdempotency(connect_go.IdempotencyNoSideEffects),
		connect_go.WithHandlerOptions(opts...),
	)
	announcementServiceGetReadFlagsHandler := connect_go.NewUnaryHandler(
		AnnouncementServiceGetReadFlagsProcedure,
		svc.GetReadFlags,
		connect_go.WithIdempotency(connect_go.IdempotencyNoSideEffects),
		connect_go.WithHandlerOptions(opts...),
	)
	announcementServiceUpdateReadFlagHandler := connect_go.NewUnaryHandler(
		AnnouncementServiceUpdateReadFlagProcedure,
		svc.UpdateReadFlag,
		opts...,
	)
	return "/announcement.v1.AnnouncementService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AnnouncementServiceGetAnnouncementsProcedure:
			announcementServiceGetAnnouncementsHandler.ServeHTTP(w, r)
		case AnnouncementServiceGetReadFlagsProcedure:
			announcementServiceGetReadFlagsHandler.ServeHTTP(w, r)
		case AnnouncementServiceUpdateReadFlagProcedure:
			announcementServiceUpdateReadFlagHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAnnouncementServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAnnouncementServiceHandler struct{}

func (UnimplementedAnnouncementServiceHandler) GetAnnouncements(context.Context, *connect_go.Request[v1.GetAnnouncementsRequest]) (*connect_go.Response[v1.GetAnnouncementsResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("announcement.v1.AnnouncementService.GetAnnouncements is not implemented"))
}

func (UnimplementedAnnouncementServiceHandler) GetReadFlags(context.Context, *connect_go.Request[v1.GetReadFlagsRequest]) (*connect_go.Response[v1.GetReadFlagsResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("announcement.v1.AnnouncementService.GetReadFlags is not implemented"))
}

func (UnimplementedAnnouncementServiceHandler) UpdateReadFlag(context.Context, *connect_go.Request[v1.UpdateReadFlagRequest]) (*connect_go.Response[v1.UpdateReadFlagResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("announcement.v1.AnnouncementService.UpdateReadFlag is not implemented"))
}
