// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: unified/v1/service.proto

package unifiedv1connect

import (
	context "context"
	errors "errors"
	connect_go "github.com/bufbuild/connect-go"
	v1 "github.com/twin-te/twinte-back/handler/api/rpcgen/unified/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion1_7_0

const (
	// UnifiedServiceName is the fully-qualified name of the UnifiedService service.
	UnifiedServiceName = "unified.v1.UnifiedService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// UnifiedServiceGetByDateProcedure is the fully-qualified name of the UnifiedService's GetByDate
	// RPC.
	UnifiedServiceGetByDateProcedure = "/unified.v1.UnifiedService/GetByDate"
)

// UnifiedServiceClient is a client for the unified.v1.UnifiedService service.
type UnifiedServiceClient interface {
	// GetByDate returns the resources related to the given date.
	// Only registered courses which will be held on the given date will be returned.
	GetByDate(context.Context, *connect_go.Request[v1.GetByDateRequest]) (*connect_go.Response[v1.GetByDateResponse], error)
}

// NewUnifiedServiceClient constructs a client for the unified.v1.UnifiedService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewUnifiedServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) UnifiedServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &unifiedServiceClient{
		getByDate: connect_go.NewClient[v1.GetByDateRequest, v1.GetByDateResponse](
			httpClient,
			baseURL+UnifiedServiceGetByDateProcedure,
			connect_go.WithIdempotency(connect_go.IdempotencyNoSideEffects),
			connect_go.WithClientOptions(opts...),
		),
	}
}

// unifiedServiceClient implements UnifiedServiceClient.
type unifiedServiceClient struct {
	getByDate *connect_go.Client[v1.GetByDateRequest, v1.GetByDateResponse]
}

// GetByDate calls unified.v1.UnifiedService.GetByDate.
func (c *unifiedServiceClient) GetByDate(ctx context.Context, req *connect_go.Request[v1.GetByDateRequest]) (*connect_go.Response[v1.GetByDateResponse], error) {
	return c.getByDate.CallUnary(ctx, req)
}

// UnifiedServiceHandler is an implementation of the unified.v1.UnifiedService service.
type UnifiedServiceHandler interface {
	// GetByDate returns the resources related to the given date.
	// Only registered courses which will be held on the given date will be returned.
	GetByDate(context.Context, *connect_go.Request[v1.GetByDateRequest]) (*connect_go.Response[v1.GetByDateResponse], error)
}

// NewUnifiedServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewUnifiedServiceHandler(svc UnifiedServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	unifiedServiceGetByDateHandler := connect_go.NewUnaryHandler(
		UnifiedServiceGetByDateProcedure,
		svc.GetByDate,
		connect_go.WithIdempotency(connect_go.IdempotencyNoSideEffects),
		connect_go.WithHandlerOptions(opts...),
	)
	return "/unified.v1.UnifiedService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case UnifiedServiceGetByDateProcedure:
			unifiedServiceGetByDateHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedUnifiedServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedUnifiedServiceHandler struct{}

func (UnimplementedUnifiedServiceHandler) GetByDate(context.Context, *connect_go.Request[v1.GetByDateRequest]) (*connect_go.Response[v1.GetByDateResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("unified.v1.UnifiedService.GetByDate is not implemented"))
}
