// Code generated by codegen/error/generate.py; DO NOT EDIT.

package timetableerr

import "github.com/twin-te/twinte-back/apperr"

const (
	CodeCourseNotFound                apperr.Code = "timetable.CourseNotFound"
	CodeRegisteredCourseAlreadyExists apperr.Code = "timetable.RegisteredCourseAlreadyExists"
	CodeRegisteredCourseNotFound      apperr.Code = "timetable.RegisteredCourseNotFound"
	CodeTagNotFound                   apperr.Code = "timetable.TagNotFound"
)
