// Code generated by "stringer -type=Permission -trimprefix=Permission -output=permission_string.gen.go"; DO NOT EDIT.

package authdomain

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PermissionExecuteBatchJob-1]
}

const _Permission_name = "ExecuteBatchJob"

var _Permission_index = [...]uint8{0, 15}

func (i Permission) String() string {
	i -= 1
	if i < 0 || i >= Permission(len(_Permission_index)-1) {
		return "Permission(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Permission_name[_Permission_index[i]:_Permission_index[i+1]]
}
