// Code generated by "stringer -type=Provider -trimprefix=Provider -output=provider_string.gen.go"; DO NOT EDIT.

package authdomain

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ProviderGoogle-1]
	_ = x[ProviderApple-2]
	_ = x[ProviderTwitter-3]
}

const _Provider_name = "GoogleAppleTwitter"

var _Provider_index = [...]uint8{0, 6, 11, 18}

func (i Provider) String() string {
	i -= 1
	if i < 0 || i >= Provider(len(_Provider_index)-1) {
		return "Provider(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Provider_name[_Provider_index[i]:_Provider_index[i+1]]
}
