// Code generated by "stringer -type=CourseMethod -trimprefix=CourseMethod -output=course_method_string.gen.go"; DO NOT EDIT.

package timetabledomain

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CourseMethodOnlineAsynchronous-1]
	_ = x[CourseMethodOnlineSynchronous-2]
	_ = x[CourseMethodFaceToFace-3]
	_ = x[CourseMethodOthers-4]
}

const _CourseMethod_name = "OnlineAsynchronousOnlineSynchronousFaceToFaceOthers"

var _CourseMethod_index = [...]uint8{0, 18, 35, 45, 51}

func (i CourseMethod) String() string {
	i -= 1
	if i < 0 || i >= CourseMethod(len(_CourseMethod_index)-1) {
		return "CourseMethod(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _CourseMethod_name[_CourseMethod_index[i]:_CourseMethod_index[i+1]]
}
