// Code generated by "stringer -type=Day -trimprefix=Day -output=day_string.gen.go"; DO NOT EDIT.

package timetabledomain

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DaySun-1]
	_ = x[DayMon-2]
	_ = x[DayTue-3]
	_ = x[DayWed-4]
	_ = x[DayThu-5]
	_ = x[DayFri-6]
	_ = x[DaySat-7]
	_ = x[DayIntensive-8]
	_ = x[DayAppointment-9]
	_ = x[DayAnyTime-10]
}

const _Day_name = "SunMonTueWedThuFriSatIntensiveAppointmentAnyTime"

var _Day_index = [...]uint8{0, 3, 6, 9, 12, 15, 18, 21, 30, 41, 48}

func (i Day) String() string {
	i -= 1
	if i < 0 || i >= Day(len(_Day_index)-1) {
		return "Day(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Day_name[_Day_index[i]:_Day_index[i+1]]
}
