// Code generated by codegen/idtype/generate.py; DO NOT EDIT.

package idtype

import (
	"fmt"

	"github.com/google/uuid"
	"github.com/samber/lo"
)

type AlreadyReadID uuid.UUID

func (id AlreadyReadID) String() string {
	return uuid.UUID(id).String()
}

func (id AlreadyReadID) IsZero() bool {
	return uuid.UUID(id) == uuid.Nil
}

func (id AlreadyReadID) Less(other AlreadyReadID) bool {
	for i := 0; i < 16; i++ {
		if id[i] == other[i] {
			continue
		}
		return id[i] < other[i]
	}
	return false
}

func (id *AlreadyReadID) StringPtr() *string {
	if id == nil {
		return nil
	}
	return lo.ToPtr(id.String())
}

func NewAlreadyReadID() AlreadyReadID {
	return AlreadyReadID(uuid.New())
}

func ParseAlreadyReadID(s string) (AlreadyReadID, error) {
	id, err := uuid.Parse(s)
	if err != nil {
		return AlreadyReadID{}, fmt.Errorf("failed to parse AlreadyReadID %#v", s)
	}
	return AlreadyReadID(id), nil
}
