// Code generated by codegen/idtype/generate.py; DO NOT EDIT.

package idtype

import (
	"fmt"

	"github.com/google/uuid"
	"github.com/samber/lo"
)

type AnnouncementID uuid.UUID

func (id AnnouncementID) String() string {
	return uuid.UUID(id).String()
}

func (id AnnouncementID) IsZero() bool {
	return uuid.UUID(id) == uuid.Nil
}

func (id AnnouncementID) Less(other AnnouncementID) bool {
	for i := 0; i < 16; i++ {
		if id[i] == other[i] {
			continue
		}
		return id[i] < other[i]
	}
	return false
}

func (id *AnnouncementID) StringPtr() *string {
	if id == nil {
		return nil
	}
	return lo.ToPtr(id.String())
}

func NewAnnouncementID() AnnouncementID {
	return AnnouncementID(uuid.New())
}

func ParseAnnouncementID(s string) (AnnouncementID, error) {
	id, err := uuid.Parse(s)
	if err != nil {
		return AnnouncementID{}, fmt.Errorf("failed to parse AnnouncementID %#v", s)
	}
	return AnnouncementID(id), nil
}
