// Code generated by codegen/idtype/generate.py; DO NOT EDIT.

package idtype

import (
	"fmt"

	"github.com/google/uuid"
	"github.com/samber/lo"
)

type CourseID uuid.UUID

func (id CourseID) String() string {
	return uuid.UUID(id).String()
}

func (id CourseID) IsZero() bool {
	return uuid.UUID(id) == uuid.Nil
}

func (id CourseID) Less(other CourseID) bool {
	for i := 0; i < 16; i++ {
		if id[i] == other[i] {
			continue
		}
		return id[i] < other[i]
	}
	return false
}

func (id *CourseID) StringPtr() *string {
	if id == nil {
		return nil
	}
	return lo.ToPtr(id.String())
}

func NewCourseID() CourseID {
	return CourseID(uuid.New())
}

func ParseCourseID(s string) (CourseID, error) {
	id, err := uuid.Parse(s)
	if err != nil {
		return CourseID{}, fmt.Errorf("failed to parse CourseID %#v", s)
	}
	return CourseID(id), nil
}
