// Code generated by codegen/idtype/generate.py; DO NOT EDIT.

package idtype

import "fmt"

type EventID int

func (id EventID) Int() int {
	return int(id)
}

func (id EventID) IsZero() bool {
	return id.Int() == 0
}

func ParseEventID(i int) (EventID, error) {
	if i == 0 {
		return 0, fmt.Errorf("failed to parse EventID %#v", i)
	}
	return EventID(i), nil
}
