// Code generated by codegen/idtype/generate.py; DO NOT EDIT.

package idtype

import "fmt"

type PaymentUserID string

func (id PaymentUserID) String() string {
	return string(id)
}

func (id PaymentUserID) IsZero() bool {
	return id == ""
}

func ParsePaymentUserID(s string) (PaymentUserID, error) {
	if s == "" {
		return "", fmt.Errorf("failed to parse PaymentUserID %#v", s)
	}
	return PaymentUserID(s), nil
}
