// Code generated by codegen/idtype/generate.py; DO NOT EDIT.

package idtype

import "fmt"

type SubscriptionPlanID string

func (id SubscriptionPlanID) String() string {
	return string(id)
}

func (id SubscriptionPlanID) IsZero() bool {
	return id == ""
}

func ParseSubscriptionPlanID(s string) (SubscriptionPlanID, error) {
	if s == "" {
		return "", fmt.Errorf("failed to parse SubscriptionPlanID %#v", s)
	}
	return SubscriptionPlanID(s), nil
}
