// Code generated by codegen/error/generate.py; DO NOT EDIT.

package autherr

import "github.com/twin-te/twinte-back/apperr"

const (
	CodeMultipleAuthenticationOfSameProvider apperr.Code = "auth.MultipleAuthenticationOfSameProvider"
	CodeUserHasAtLeastOneAuthentication      apperr.Code = "auth.UserHasAtLeastOneAuthentication"
)
